Repository AFM-SPM/TopoStats, pull requests merged in 2024-12, with the labels that each got.

#1045 Remove index column from results plus some other tidying
  .gitignore
  topostats/run_modules.py
  topostats/tracing/ordered_tracing.py
Labels: v2.3.0

#1040 doc: Updates the data dictionary
  docs/advanced/disordered_tracing.md
  docs/data_dictionary.md
Labels: v2.3.0

#1030 Modifies the squaring bbox and tweaks PIL input shapes
  tests/test_unet_masking.py
  topostats/grains.py
  topostats/unet_masking.py
Labels: v2.3.0

#1042 Enables legacy unets to run
  topostats/grains.py
  topostats/unet_masking.py
Labels: v2.3.0

#1047 Returns grainstats rows when tracing for a grain fails
  tests/_regtest_outputs/test_processing.test_process_scan_both.out
  topostats/processing.py
Labels: bug, v2.3.0

#1051 Refactor smooth_mask to take null values
  docs/advanced/disordered_tracing.md
  tests/tracing/conftest.py
  tests/tracing/test_disordered_tracing.py
  topostats/tracing/disordered_tracing.py
Labels: enhancement, v2.3.0

#1048 Adds nbQA to pre-commit hooks
  .pre-commit-config.yaml
  notebooks/OUTDATED-00-Walkthrough-minicircle.ipynb
  notebooks/OUTDATED-02-Summary-statistics-and-plots.ipynb
  notebooks/OUTDATED-03-Plotting-scans.ipynb
  tox.ini
Labels: CI/CD, v2.3.0

#1049 chore: Remove unused method, test and package dependencies
  pyproject.toml
  tests/conftest.py
  tests/test_io.py
  topostats/io.py
Labels: IO, tests, v2.3.0

#1053 style(notebooks): Ignore Flake8 complaints on Notebooks
  notebooks/OUTDATED-02-Summary-statistics-and-plots.ipynb
  notebooks/OUTDATED-03-Plotting-scans.ipynb
Labels: v2.3.0

#1052 refactor(disordered_tracing): Work with skan-0.12.2
  pyproject.toml
  topostats/tracing/disordered_tracing.py
Labels: DNATracing, v2.3.0

#1055 chore: Clarify request for log output in bug reports
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: enhancement

#1058 feature: Adds --image-set as option to topostats
  topostats/entry_point.py
Labels: enhancement, ui

#1060 ci(pypi) adding write permissions to PyPI workflow
  .github/workflows/pypi.yaml
Labels: CI/CD

#1065 Tidy up package and build with only necessary files
  MANIFEST.in
  assets/commit.png
  assets/issues-prs.png
  assets/pull-request.png
  assets/push.png
  assets/pycharm-branch.png
  assets/stage.png
Labels: CI/CD
