Repository AFM-SPM/TopoStats, pull requests merged in 2024-11, with the labels that each got.

#981 Add support for partial config files
  docs/configuration.md
  tests/resources/test_partial_config.yaml
  tests/test_entry_point.py
  tests/test_io.py
  tests/test_run_topostats.py
  topostats/default_config.yaml
  topostats/entry_point.py
  topostats/io.py
  topostats/run_topostats.py
  topostats/simple_config.yaml
Labels: enhancement

#988 wip: Adding all configuration options as arguments
  pyproject.toml
  tests/test_entry_point.py
  tests/test_plotting.py
  tests/test_run_modules.py
  topostats/default_config.yaml
  topostats/entry_point.py
  topostats/plotting.py
  topostats/processing.py
  topostats/run_modules.py
Labels: enhancement

#1000 ci: Adds a Pull Request template
  .github/pull_request_template.md
Labels: CI/CD

#995 package: Unpin topoly version
  pyproject.toml
  tests/resources/tracing/ordered_tracing/catenanes_ordered_tracing_data.pkl
  tests/resources/tracing/ordered_tracing/catenanes_ordered_tracing_molstats.csv
Labels: packaging

#1011 style: Changes prettier mirror used by pre-commit
  .pre-commit-config.yaml
Labels: v2.3.0

#1012 dependabot for GitHub Actions
  .github/dependabot.yml
  .github/pull_request_template.md
Labels: v2.3.0

#1013 config: Removes target-version from ruff configuration
  pyproject.toml
Labels: v2.3.0
