Repository AFM-SPM/TopoStats, pull requests merged in 2025-02, with the labels that each got.

#1078 docs: Clearer workflow overview
  docs/workflow.md
Labels: documentation

#1091 fix: Updates io to work with AFMReader only returning data
  pyproject.toml
  tests/test_filters.py
  tests/test_io.py
  tests/test_run_modules.py
  topostats/io.py
Labels: IO, refactor

#1092 style: using dictionaries for parameters and **kwargs
  tests/test_grains.py
  tests/test_processing.py
Labels: enhancement

#1087 Added rough grainstats summary documentation and metric images
  docs/_static/images/disordered_tracing/ts2_dis_metrics.png
  docs/_static/images/disordered_tracing/ts2_metrics-branch.png
  docs/_static/images/grainstats/ts2_gs_metrics.png
  docs/_static/images/nodestats/ts2_ns_metrics.png
  docs/_static/images/ordered_tracing/ts2_metrics-mols.png
  docs/_static/images/ordered_tracing/ts2_ord_metrics.png
  docs/_static/images/splining/ts2_metrics-mols_1.png
  docs/_static/images/splining/ts2_sp_metrics.png
  docs/advanced.md
  docs/advanced/disordered_tracing.md
  docs/advanced/grainstats.md
  docs/advanced/nodestats.md
  docs/advanced/ordered_tracing.md
  docs/advanced/splining.md
Labels: documentation
